"""Initial schema

Revision ID: bc4efd392c8d
Revises: 
Create Date: 2026-07-24 09:59:39.896800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4efd392c8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('filesize', sa.BigInteger(), nullable=False),
    sa.Column('storage_method', sa.Enum('filesystem', 'blob', name='storage_method_enum'), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.Column('upload_duration_ms', sa.Float(), nullable=True),
    sa.Column('last_retrieval_duration_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_storage_method'), ['storage_method'], unique=False)

    op.create_table('image_blobs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('image_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('image_data', sa.LargeBinary(length=4294967295), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_blobs')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_storage_method'))

    op.drop_table('images')
    # ### end Alembic commands ###
